### ISSUE TITLE
Some exception occurred while processing "xxxxx"

### ISSUE THREAD

**Issue by two-cees** [pkMinhas/SP404WavConvertor#1]
I receive this error message for every file on an M1 MacBook. Tried running sudo. Checked folder permissions.

**Comment by pkMinhas** [comment]
Will investigate this and get back to you.

**Comment by pkMinhas** [comment]
It appears that you do not have FFmpeg in your $PATH. Please confirm.

**Comment by two-cees** [comment]
I believe I did, but I reinstalled just to be sure. Now I am receiving an error saying "no module named 'ffmpeg'" though I can run ffmpeg from my terminal.

**Comment by two-cees** [comment]
Nevermind worked after installing ffmpeg-python with pip3 instead of pip.
